# LaTeX2HTML 96.1 (Feb 5, 1996)
# Associate images original text with physical files.

$key = q/{figure}[H]hspace*3.5cmincludegraphicshomespmadammHPCHPFCourseDiagramsProcessorGrid.epslabel2DProcessorGrid:fig{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=194 HEIGHT=194 ALIGN=BOTTOM ALT="figure12266" SRC="HTMLSlidesimg80.gif"  > '; 
$key = q/{figure}[H]hspace*3.0cmincludegraphicshomespmadammHPCHPFCourseDiagramsAlignAB.pslabelAlignmentVisualisation:fig{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=439 HEIGHT=270 ALIGN=BOTTOM ALT="figure13654" SRC="HTMLSlidesimg104.gif"  > '; 
$key = q/{figure}centerincludegraphicshomespmadammHPCF90CourseDiagramsArraySectionsFigurecenter{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=437 HEIGHT=391 ALIGN=BOTTOM ALT="figure7130" SRC="HTMLSlidesimg28.gif"  > '; 
$key = q/{displaymath}ttTSOURCE=left(arrayccc1;SPMamp;5;SPMamp;93;SPMamp;7;SPMamp;11arrayright){displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=325 HEIGHT=33 ALIGN=BOTTOM ALT="displaymath22075" SRC="HTMLSlidesimg64.gif"  > '; 
$key = q/{figure}[H]centerscalebox0.66includegraphicshomespmadammHPCHPFCourseDiagramsNewVariables1.pslabelINDEPENDENTNEWVisualisation:figcenter{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=461 HEIGHT=213 ALIGN=BOTTOM ALT="figure15732" SRC="HTMLSlidesimg134.gif"  > '; 
$key = q/{_inline}$leq|1|${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=26 HEIGHT=21 ALIGN=MIDDLE ALT="tex2html_wrap_inline21322" SRC="HTMLSlidesimg15.gif"  > '; 
$key = q/{}includegraphicshomespmadammHPCHPFCourseDiagramsProcessorChain.eps{}/;
$cached_env_img{$key} = ' <IMG WIDTH=388 HEIGHT=49 ALIGN=BOTTOM ALT="tex2html_wrap22226" SRC="HTMLSlidesimg81.gif"  > '; 
$key = q/{}includegraphicshomespmadammHPCHPFCourseDiagramsGaussF90Replication{}/;
$cached_env_img{$key} = ' <IMG WIDTH=582 HEIGHT=588 ALIGN=BOTTOM ALT="tex2html_wrap22430" SRC="HTMLSlidesimg121.gif"  > '; 
$key = q/{figure}[H]hspace*-0.2cmcenterincludegraphicshomespmadammHPCHPFCourseDiagramsGaussF90Replicationcenterlabel2DGaussianEliminationVisualisation{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=582 HEIGHT=588 ALIGN=BOTTOM ALT="figure14419" SRC="HTMLSlidesimg121.gif"  > '; 
$key = q/{displaymath}ttUNPACK((3,2,1),.NOT.MASK,FIELD)=left(arrayrrr9;SPMamp;5;SPMamp;fbox1fbox3;SPMamp;fbox2;SPMamp;3arrayright){displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=419 HEIGHT=41 ALIGN=BOTTOM ALT="displaymath22179" SRC="HTMLSlidesimg76.gif"  > '; 
$key = q/{}includegraphicshomespmadammHPCHPFCourseDiagramsPassingSectionsActuals{}/;
$cached_env_img{$key} = ' <IMG WIDTH=498 HEIGHT=204 ALIGN=BOTTOM ALT="tex2html_wrap22542" SRC="HTMLSlidesimg141.gif"  > '; 
$key = q/{_inline}$r_i${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=9 HEIGHT=12 ALIGN=MIDDLE ALT="tex2html_wrap_inline22584" SRC="HTMLSlidesimg149.gif"  > '; 
$key = q/{}epsfigfigure=homespmadammHPCF90CourseDiagramsMainProgramDiagram{}/;
$cached_env_img{$key} = ' <IMG WIDTH=316 HEIGHT=485 ALIGN=BOTTOM ALT="tex2html_wrap21750" SRC="HTMLSlidesimg51.gif"  > '; 
$key = q/{_inline}$128times128times128${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=92 HEIGHT=18 ALIGN=MIDDLE ALT="tex2html_wrap_inline22620" SRC="HTMLSlidesimg165.gif"  > '; 
$key = q/{}(lceil#A#Prceil){}/;
$cached_env_img{$key} = ' <IMG WIDTH=58 HEIGHT=14 ALIGN=BOTTOM ALT="tex2html_wrap22248" SRC="HTMLSlidesimg90.gif"  > '; 
$key = q/{_inline}$pi${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=8 HEIGHT=6 ALIGN=BOTTOM ALT="tex2html_wrap_inline20618" SRC="HTMLSlidesimg9.gif"  > '; 
$key = q/{table}[H]centercentertabular|l|l|r|r|r|r|r|hlinembox;SPMamp;multicolumn5cNumberofProcessors;SPMamp;Compiler;SPMamp;_inline$1times1times1$_inline;SPMamp;_inline$2times1times1$_inline;SPMamp;_inline$2times2times1$_inline;SPMamp;_inline$2times2times2$_inline;SPMamp;_inline$4times2times2$_inlinehlinehlinebfSun;SPMamp;Adaptor;SPMamp;85.17;SPMamp;56.68;SPMamp;31.75;SPMamp;21.56;SPMamp;19.19;SPMamp;APRxHPF;SPMamp;105.12;SPMamp;51.41;SPMamp;27.75;SPMamp;19.12;SPMamp;-;SPMamp;PGI;SPMamp;94.55;SPMamp;71.69;SPMamp;38.73;SPMamp;22.78;SPMamp;30.05cline2-7;SPMamp;epcf90;SPMamp;114.75;SPMamp;-;SPMamp;-;SPMamp;-;SPMamp;-;SPMamp;NAgf90;SPMamp;121.00;SPMamp;-;SPMamp;-;SPMamp;-;SPMamp;-;SPMamp;Fujif90;SPMamp;112.68;SPMamp;-;SPMamp;-;SPMamp;-;SPMamp;-hlinehlinebfSGI;SPMamp;epcf90;SPMamp;37.12;SPMamp;-;SPMamp;-;SPMamp;-;SPMamp;-;SPMamp;SGIf90;SPMamp;25.14;SPMamp;-;SPMamp;-;SPMamp;-;SPMamp;-cline2-7;SPMamp;PGI;SPMamp;38.91;SPMamp;52.47;SPMamp;34.67;SPMamp;25.86;SPMamp;-hlinetabularlabelPDE1:uxa:Tabcentercenter{table}/;
$cached_env_img{$key} = ' <IMG WIDTH=473 HEIGHT=185 ALIGN=BOTTOM ALT="table18409" SRC="HTMLSlidesimg166.gif"  > '; 
$key = q/{}epsfigfigure=homespmadammHPCF90CourseDiagramsHowAStackWorks{}/;
$cached_env_img{$key} = ' <IMG WIDTH=388 HEIGHT=291 ALIGN=BOTTOM ALT="tex2html_wrap22010" SRC="HTMLSlidesimg55.gif"  > '; 
$key = q/{tabular}|r|l|r|hlineSource;SPMamp;Compiler;SPMamp;ExecTime(s)hlinehlinebff90;SPMamp;EPC;SPMamp;85.0;SPMamp;Sun(_inline$parallel$_inline)(1proc);SPMamp;111.0;SPMamp;Sun(_inline$parallel$_inline)(2proc);SPMamp;111.0hlinebfhpf;SPMamp;PGI(_inline$parallel$_inline)(1proc);SPMamp;127.5;SPMamp;PGI(_inline$parallel$_inline)(2proc);SPMamp;67.6hline{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=269 HEIGHT=101 ALIGN=BOTTOM ALT="tabular18393" SRC="HTMLSlidesimg148.gif"  > '; 
$key = q/{}includegraphicshomespmadammHPCHPFCourseDiagramsAlignToSection.ps{}/;
$cached_env_img{$key} = ' <IMG WIDTH=212 HEIGHT=264 ALIGN=BOTTOM ALT="tex2html_wrap22450" SRC="HTMLSlidesimg126.gif"  > '; 
$key = q/{}includegraphicshomespmadammHPCHPFCourseDiagramsCyclicDistribution.ps{}/;
$cached_env_img{$key} = ' <IMG WIDTH=603 HEIGHT=218 ALIGN=BOTTOM ALT="tex2html_wrap22278" SRC="HTMLSlidesimg93.gif"  > '; 
$key = q/{}includegraphicshomespmadammHPCF90CourseDiagramsArrayElementOrderingFigure{}/;
$cached_env_img{$key} = ' <IMG WIDTH=292 HEIGHT=324 ALIGN=BOTTOM ALT="tex2html_wrap21380" SRC="HTMLSlidesimg25.gif"  > '; 
$key = q/{_inline}$10^4${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=18 HEIGHT=12 ALIGN=BOTTOM ALT="tex2html_wrap_inline20502" SRC="HTMLSlidesimg5.gif"  > '; 
$key = q/{}fboxRemember{}/;
$cached_env_img{$key} = ' <IMG WIDTH=73 HEIGHT=19 ALIGN=BOTTOM ALT="tex2html_wrap22452" SRC="HTMLSlidesimg127.gif"  > '; 
$key = q/{_inline}$t_j=x^2_j+y^2_jleq1${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=95 HEIGHT=22 ALIGN=MIDDLE ALT="tex2html_wrap_inline22604" SRC="HTMLSlidesimg158.gif"  > '; 
$key = q/{_inline}$(x_j,y_j)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=40 HEIGHT=21 ALIGN=MIDDLE ALT="tex2html_wrap_inline22602" SRC="HTMLSlidesimg157.gif"  > '; 
$key = q/{_inline}$10times10${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=42 HEIGHT=18 ALIGN=MIDDLE ALT="tex2html_wrap_inline20550" SRC="HTMLSlidesimg8.gif"  > '; 
$key = q/{table}[H]centercentertabular|l|l|r|r|r|r|hline;SPMamp;multicolumn4cNumberofProcessors;SPMamp;Compiler;SPMamp;1;SPMamp;2;SPMamp;4;SPMamp;8hlinehlinebfSun;SPMamp;PGI;SPMamp;2.51;SPMamp;2.41;SPMamp;2.17;SPMamp;2.93;SPMamp;APRxHPF;SPMamp;5.06;SPMamp;7.63;SPMamp;;SPMamp;hline;SPMamp;epcf90;SPMamp;0.1016;SPMamp;-;SPMamp;-;SPMamp;-;SPMamp;Fujif90;SPMamp;0.0742;SPMamp;-;SPMamp;-;SPMamp;-hlinebfSGI;SPMamp;SGIPGI;SPMamp;0.70;SPMamp;2.28;SPMamp;3.42;SPMamp;5.43hline;SPMamp;SGIF90;SPMamp;0.16;SPMamp;-;SPMamp;-;SPMamp;-hlinetabularlabelFFT1:uxa:Tabcentercenter{table}/;
$cached_env_img{$key} = ' <IMG WIDTH=301 HEIGHT=135 ALIGN=BOTTOM ALT="table18413" SRC="HTMLSlidesimg167.gif"  > '; 
$key = q/{}includegraphicshomespmadammHPCF90CourseDiagramsArrayConformanceDiagram{}/;
$cached_env_img{$key} = ' <IMG WIDTH=291 HEIGHT=291 ALIGN=BOTTOM ALT="tex2html_wrap21386" SRC="HTMLSlidesimg27.gif"  > '; 
$key = q/{displaymath}mboxttB=left(arraycc1.0;SPMamp;2.03.0;SPMamp;4.0arrayright){displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=301 HEIGHT=33 ALIGN=BOTTOM ALT="displaymath21536" SRC="HTMLSlidesimg37.gif"  > '; 
$key = q/{}includegraphicshomespmadammHPCHPFCourseDiagramsNewAlignTemplateDCE.ps{}/;
$cached_env_img{$key} = ' <IMG WIDTH=256 HEIGHT=618 ALIGN=BOTTOM ALT="tex2html_wrap22438" SRC="HTMLSlidesimg125.gif"  > '; 
$key = q/{}fboxDonotpassarraysections{}/;
$cached_env_img{$key} = ' <IMG WIDTH=165 HEIGHT=21 ALIGN=BOTTOM ALT="tex2html_wrap22554" SRC="HTMLSlidesimg144.gif"  > '; 
$key = q/{displaymath}ttMASK=left(arraycccT;SPMamp;T;SPMamp;FF;SPMamp;F;SPMamp;Tarrayright){displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=319 HEIGHT=33 ALIGN=BOTTOM ALT="displaymath22074" SRC="HTMLSlidesimg63.gif"  > '; 
$key = q/{}includegraphicshomespmadammHPCHPFCourseDiagramsProcessorGrid.eps{}/;
$cached_env_img{$key} = ' <IMG WIDTH=194 HEIGHT=194 ALIGN=BOTTOM ALT="tex2html_wrap22224" SRC="HTMLSlidesimg80.gif"  > '; 
$key = q/{figure}[H]includegraphicshomespmadammHPCHPFCourseDiagramsBlockCyclicDistribution.pslabel2DDistributionVisualisation:fig{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=401 HEIGHT=295 ALIGN=BOTTOM ALT="figure12752" SRC="HTMLSlidesimg95.gif"  > '; 
$key = q/{figure}[H]centerincludegraphicshomespmadammHPCF90CourseDiagramsVectorSubscriptsDiagramcenter{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=364 HEIGHT=178 ALIGN=BOTTOM ALT="figure7931" SRC="HTMLSlidesimg42.gif"  > '; 
$key = q/{_inline}$times${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=7 HEIGHT=13 ALIGN=MIDDLE ALT="tex2html_wrap_inline22574" SRC="HTMLSlidesimg147.gif"  > '; 
$key = q/{}scalebox0.8includegraphicshomespmadammHPCHPFCourseDiagramsNewVariables1.ps{}/;
$cached_env_img{$key} = ' <IMG WIDTH=557 HEIGHT=257 ALIGN=BOTTOM ALT="tex2html_wrap22522" SRC="HTMLSlidesimg133.gif"  > '; 
$key = q/{figure}[H]hspace*0.0cmincludegraphicshomespmadammHPCHPFCourseDiagramsBlockMCyclicMDistribution.pslabelBLOCKmCYCLICmDistribution:fig{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=597 HEIGHT=297 ALIGN=BOTTOM ALT="figure13307" SRC="HTMLSlidesimg100.gif"  > '; 
$key = q/{}includegraphicshomespmadammHPCF90CourseDiagramsArrayFigures{}/;
$cached_env_img{$key} = ' <IMG WIDTH=333 HEIGHT=318 ALIGN=BOTTOM ALT="tex2html_wrap21376" SRC="HTMLSlidesimg21.gif"  > '; 
$key = q/{}epsfigfigure=homespmadammHPCF90CourseDiagramsSubroutineDiagram{}/;
$cached_env_img{$key} = ' <IMG WIDTH=316 HEIGHT=364 ALIGN=BOTTOM ALT="tex2html_wrap21810" SRC="HTMLSlidesimg52.gif"  > '; 
$key = q/{displaymath}mboxttI=left(arrayccfbox2;SPMamp;sf0sf0;SPMamp;fbox2arrayright){displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=300 HEIGHT=41 ALIGN=BOTTOM ALT="displaymath21540" SRC="HTMLSlidesimg41.gif"  > '; 
$key = q/{}includegraphicshomespmadammHPCHPFCourseDiagramsScalarAlignment.ps{}/;
$cached_env_img{$key} = ' <IMG WIDTH=266 HEIGHT=330 ALIGN=BOTTOM ALT="tex2html_wrap22458" SRC="HTMLSlidesimg129.gif"  > '; 
$key = q/{figure}[H]hspace*3.0cmincludegraphicshomespmadammHPCHPFCourseDiagrams2DBlockMCyclicMDistribution.pslabel2DBlockMCyclicMDistribution{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=351 HEIGHT=421 ALIGN=BOTTOM ALT="figure13368" SRC="HTMLSlidesimg103.gif"  > '; 
$key = q/{}includegraphicshomespmadammHPCF90CourseDiagramsArraySectionsFigure{}/;
$cached_env_img{$key} = ' <IMG WIDTH=437 HEIGHT=391 ALIGN=BOTTOM ALT="tex2html_wrap21522" SRC="HTMLSlidesimg28.gif"  > '; 
$key = q/{_inline}$Y_k${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=13 HEIGHT=19 ALIGN=MIDDLE ALT="tex2html_wrap_inline22608" SRC="HTMLSlidesimg162.gif"  > '; 
$key = q/{}includegraphicshomespmadammHPCHPFCourseDiagramsStridedAlignment.ps{}/;
$cached_env_img{$key} = ' <IMG WIDTH=267 HEIGHT=212 ALIGN=BOTTOM ALT="tex2html_wrap22406" SRC="HTMLSlidesimg113.gif"  > '; 
$key = q/{displaymath}X_k=x_jsqrt(-2logt_j)t_j{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=319 HEIGHT=25 ALIGN=BOTTOM ALT="displaymath22570" SRC="HTMLSlidesimg159.gif"  > '; 
$key = q/{displaymath}ttA=left(arraycccfbox1;SPMamp;fbox5;SPMamp;93;SPMamp;7;SPMamp;fbox11arrayright){displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=319 HEIGHT=41 ALIGN=BOTTOM ALT="displaymath22117" SRC="HTMLSlidesimg72.gif"  > '; 
$key = q/{_inline}$10^158${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=28 HEIGHT=11 ALIGN=BOTTOM ALT="tex2html_wrap_inline20498" SRC="HTMLSlidesimg3.gif"  > '; 
$key = q/{displaymath}B=left(arraycc4;SPMamp;83;SPMamp;72;SPMamp;61;SPMamp;5arrayright){displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=294 HEIGHT=65 ALIGN=BOTTOM ALT="displaymath21589" SRC="HTMLSlidesimg46.gif"  > '; 
$key = q/{figure}[H]hspace*3.0cmincludegraphicshomespmadammHPCHPFCourseDiagramsReverseStridedAlignment.pslabelReverseStridedAlignmentVisualisation:fig{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=282 HEIGHT=206 ALIGN=BOTTOM ALT="figure13979" SRC="HTMLSlidesimg115.gif"  > '; 
$key = q/{}fboxAlwaysspecifyttINTENT.{}/;
$cached_env_img{$key} = ' <IMG WIDTH=146 HEIGHT=22 ALIGN=BOTTOM ALT="tex2html_wrap22540" SRC="HTMLSlidesimg140.gif"  > '; 
$key = q/{figure}[H]includegraphicshomespmadammHPCHPFCourseDiagramsReplicatedDistribution.pslabelSTARDistributionVisualisation:fig{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=332 HEIGHT=295 ALIGN=BOTTOM ALT="figure12790" SRC="HTMLSlidesimg96.gif"  > '; 
$key = q/{}epsfigfigure=homespmadammHPCF90CourseDiagramsVectorSubscriptsDiagram{}/;
$cached_env_img{$key} = ' <IMG WIDTH=364 HEIGHT=178 ALIGN=BOTTOM ALT="tex2html_wrap21564" SRC="HTMLSlidesimg42.gif"  > '; 
$key = q/{_inline}$3times3${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=29 HEIGHT=18 ALIGN=MIDDLE ALT="tex2html_wrap_inline21488" SRC="HTMLSlidesimg30.gif"  > '; 
$key = q/{tabular}|l|p3.5in|hlinettACOStt(x);SPMamp;arccosinettASINtt(x);SPMamp;arcsinettATANtt(x);SPMamp;arctangentttATAN2tt(y,x);SPMamp;arctangentofcomplexnumber_inline$(x,y)$_inlinettCOStt(x);SPMamp;cosinewhere_inline$x$_inlineisinradiansttCOSHtt(x);SPMamp;hyperboliccosinewhere_inline$x$_inlineisinradiansttEXPtt(x);SPMamp;_inline$e$_inlineraisedtothepower_inline$x$_inlinettLOGtt(x);SPMamp;naturallogarithmof_inline$x$_inlinettLOG10tt(x);SPMamp;logarithmbase10of_inline$x$_inlinettSINtt(x);SPMamp;sinewhere_inline$x$_inlineisinradiansttSINHtt(x);SPMamp;hyperbolicsinewhere_inline$x$_inlineisinradiansttSQRTtt(x);SPMamp;thesquarerootof_inline$x$_inlinettTANtt(x);SPMamp;tangentwhere_inline$x$_inlineisinradiansttTANHtt(x);SPMamp;tangentwhere_inline$x$_inlineisinradianshline{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=442 HEIGHT=226 ALIGN=BOTTOM ALT="tabular6040" SRC="HTMLSlidesimg14.gif"  > '; 
$key = q/{tabular}|p1in|p1.5in|p2.5in|hlinemulticolumn3|c|multicolumn3|c|ttPROGRAM,ttFUNCTION,ttSUB-ROUTINE,ttMODULEorttBLOCKttDATAstatementmulticolumn3|c|hlinemulticolumn3|c|multicolumn3|c|ttUSEstatementmulticolumn3|c|hline;SPMamp;multicolumn2c|;SPMamp;multicolumn2c|ttIMPLICITttNONE;SPMamp;multicolumn2c|cline2-3;SPMamp;;SPMamp;;SPMamp;ttPARA-METERstatement;SPMamp;ttIMPLICITstatements;SPMamp;;SPMamp;cline2-3;SPMamp;;SPMamp;ttFORMATandttENTRYstatements;SPMamp;ttPARA-METERandttDATAstatements;SPMamp;Derived-TypeDefinition,Interfaceblocks,Typedeclarationstatements,Statementfunctionstatementsandspecificationstatements;SPMamp;;SPMamp;cline2-3;SPMamp;;SPMamp;;SPMamp;ttDATAstatements;SPMamp;Executableconstructs;SPMamp;;SPMamp;hlinemulticolumn3|c|multicolumn3|c|ttCONT-AINSstatementmulticolumn3|c|hlinemulticolumn3|c|multicolumn3|c|Internalormoduleproceduresmulticolumn3|c|hlinemulticolumn3|c|multicolumn3|c|ttENDstatementmulticolumn3|c|hline{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=533 HEIGHT=486 ALIGN=BOTTOM ALT="tabular2350" SRC="HTMLSlidesimg7.gif"  > '; 
$key = q/{figure}[H]hspace*3.0cmincludegraphicshomespmadammHPCHPFCourseDiagramsReplicatedAlignment.pslabelReplicatedAlignmentVisualisation:fig{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=243 HEIGHT=312 ALIGN=BOTTOM ALT="figure14314" SRC="HTMLSlidesimg119.gif"  > '; 
$key = q/{displaymath}ttMERGEtt(ttTSOURCE,ttFSOURCE,ttMASKtt)=left(arrayccc1;SPMamp;5;SPMamp;82;SPMamp;6;SPMamp;11arrayright){displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=393 HEIGHT=33 ALIGN=BOTTOM ALT="displaymath22081" SRC="HTMLSlidesimg69.gif"  > '; 
$key = q/{_inline}$0leqx;SPMlt;1${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=56 HEIGHT=19 ALIGN=MIDDLE ALT="tex2html_wrap_inline21568" SRC="HTMLSlidesimg44.gif"  > '; 
$key = q/{_inline}$amboxmodb${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=39 HEIGHT=10 ALIGN=BOTTOM ALT="tex2html_wrap_inline21362" SRC="HTMLSlidesimg19.gif"  > '; 
$key = q/{}includegraphicshomespmadammHPCHPFCourseDiagramsAlignTemplateAB.ps{}/;
$cached_env_img{$key} = ' <IMG WIDTH=374 HEIGHT=270 ALIGN=BOTTOM ALT="tex2html_wrap22434" SRC="HTMLSlidesimg123.gif"  > '; 
$key = q/{figure}[H]centerincludegraphicshomespmadammHPCHPFCourseDiagramsPassingSectionsActualslabelDistributionActualDummyArgumentsVisualisation:figcenter{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=498 HEIGHT=204 ALIGN=BOTTOM ALT="figure16573" SRC="HTMLSlidesimg141.gif"  > '; 
$key = q/{figure}[H]hspace*3.0cmincludegraphicshomespmadammHPCHPFCourseDiagramsProcessorChain.epslabel1DProcessorChain:fig{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=388 HEIGHT=49 ALIGN=BOTTOM ALT="figure12272" SRC="HTMLSlidesimg81.gif"  > '; 
$key = q/{tabular}cccvspace2mmbfCategory;SPMamp;bfOperator;SPMamp;bfPrecedencevspace2mmExtension;SPMamp;user-definedmonadic;SPMamp;Highestvspace2mmNumeric;SPMamp;tt*tt*;SPMamp;_inline$cdot$_inlinevspace2mmNumeric;SPMamp;tt*ortt;SPMamp;_inline$cdot$_inlinevspace3mmNumeric;SPMamp;monadictt+ortt-;SPMamp;_inline$cdot$_inlinevspace2mmNumeric;SPMamp;dyadictt+ortt-;SPMamp;_inline$cdot$_inlinevspace2mmCharacter;SPMamp;tttt;SPMamp;_inline$cdot$_inlinevspace2mmRelational;SPMamp;tt.GT.,tt.GE.,tt.LE.,tt.LT.,tt.EQ.ortt.NE.;SPMamp;_inline$cdot$_inlinevspace2mmLogical;SPMamp;tt.NOT.;SPMamp;_inline$cdot$_inlinevspace2mmLogical;SPMamp;tt.AND.;SPMamp;_inline$cdot$_inlinevspace2mmLogical;SPMamp;tt.OR.;SPMamp;_inline$cdot$_inlinevspace2mmLogical;SPMamp;tt.EQV.ortt.NEQV.;SPMamp;_inline$cdot$_inlinevspace2mmExtension;SPMamp;user-defineddyadic;SPMamp;Lowestvspace2mm{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=387 HEIGHT=302 ALIGN=BOTTOM ALT="tabular3641" SRC="HTMLSlidesimg11.gif"  > '; 
$key = q/{_inline}$e^x${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=11 HEIGHT=8 ALIGN=BOTTOM ALT="tex2html_wrap_inline21326" SRC="HTMLSlidesimg17.gif"  > '; 
$key = q/{displaymath}ttTSOURCE=left(arraycccfbox1;SPMamp;fbox5;SPMamp;93;SPMamp;7;SPMamp;fbox11arrayright){displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=342 HEIGHT=41 ALIGN=BOTTOM ALT="displaymath22079" SRC="HTMLSlidesimg67.gif"  > '; 
$key = q/{displaymath}A=left(arrayccc1;SPMamp;3;SPMamp;52;SPMamp;4;SPMamp;6arrayright){displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=302 HEIGHT=33 ALIGN=BOTTOM ALT="displaymath21654" SRC="HTMLSlidesimg49.gif"  > '; 
$key = q/{displaymath}ttMERGEtt(ttTSOURCE,ttFSOURCE,ttMASKtt)=left(arraycccfbox1;SPMamp;fbox5;SPMamp;82;SPMamp;6;SPMamp;fbox11arrayright){displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=407 HEIGHT=41 ALIGN=BOTTOM ALT="displaymath22077" SRC="HTMLSlidesimg66.gif"  > '; 
$key = q/{figure}[H]centerrotatebox270scalebox0.6includegraphicshomespmadammHPCHPFCourseDiagramsNewVariablesExample1.pscenterlabelDoubleNestedIndepentLoop:fig{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=495 HEIGHT=306 ALIGN=BOTTOM ALT="figure15882" SRC="HTMLSlidesimg137.gif"  > '; 
$key = q/{}fboxMustavoidnon-essentialremapping.{}/;
$cached_env_img{$key} = ' <IMG WIDTH=225 HEIGHT=22 ALIGN=BOTTOM ALT="tex2html_wrap22538" SRC="HTMLSlidesimg139.gif"  > '; 
$key = q/{displaymath}mboxttA=left(arrayccfbox0.5;SPMamp;cdotcdot;SPMamp;fbox2.0arrayright){displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=311 HEIGHT=41 ALIGN=BOTTOM ALT="displaymath21538" SRC="HTMLSlidesimg39.gif"  > '; 
$key = q/{figure}[H]hspace*3.0cmincludegraphicshomespmadammHPCHPFCourseDiagramsCollapsedAlignment.pslabelCollapsingDimensionVisualisation:fig{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=218 HEIGHT=325 ALIGN=BOTTOM ALT="figure14226" SRC="HTMLSlidesimg117.gif"  > '; 
$key = q/{_inline}$x_j=2r_2j-1-1${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=91 HEIGHT=18 ALIGN=MIDDLE ALT="tex2html_wrap_inline22592" SRC="HTMLSlidesimg153.gif"  > '; 
$key = q/{figure}[H]centerincludegraphicshomespmadammHPCF90CourseDiagramsHowAStackWorkscenter{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=388 HEIGHT=291 ALIGN=BOTTOM ALT="figure10681" SRC="HTMLSlidesimg55.gif"  > '; 
$key = q/{}includegraphicshomespmadammHPCHPFCourseDiagrams2DBlockMCyclicMDistribution.ps{}/;
$cached_env_img{$key} = ' <IMG WIDTH=351 HEIGHT=421 ALIGN=BOTTOM ALT="tex2html_wrap22374" SRC="HTMLSlidesimg102.gif"  > '; 
$key = q/{figure}[H]includegraphicshomespmadammHPCHPFCourseDiagramsBlockDistribution.pslabelBLOCKDistributionVisualisation:fig{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=591 HEIGHT=193 ALIGN=BOTTOM ALT="figure12690" SRC="HTMLSlidesimg91.gif"  > '; 
$key = q/{figure}[H]hspace*3.0cmincludegraphicshomespmadammHPCHPFCourseDiagramsAlignTemplateAB.pslabelTemplateAlignmentVisualisation:fig{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=374 HEIGHT=270 ALIGN=BOTTOM ALT="figure14557" SRC="HTMLSlidesimg123.gif"  > '; 
$key = q/{_inline}$7^th${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=16 HEIGHT=12 ALIGN=BOTTOM ALT="tex2html_wrap_inline21370" SRC="HTMLSlidesimg20.gif"  > '; 
$key = q/{_inline}$X_k${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=16 HEIGHT=19 ALIGN=MIDDLE ALT="tex2html_wrap_inline22606" SRC="HTMLSlidesimg161.gif"  > '; 
$key = q/{displaymath}Y_k=y_jsqrt(-2logt_j)t_j{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=317 HEIGHT=25 ALIGN=BOTTOM ALT="displaymath22571" SRC="HTMLSlidesimg160.gif"  > '; 
$key = q/{}includegraphicshomespmadammHPCHPFCourseDiagramsReplicatedDistribution.ps{}/;
$cached_env_img{$key} = ' <IMG WIDTH=332 HEIGHT=295 ALIGN=BOTTOM ALT="tex2html_wrap22286" SRC="HTMLSlidesimg96.gif"  > '; 
$key = q/{_inline}$!;SPMgt;${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=8 HEIGHT=17 ALIGN=MIDDLE ALT="tex2html_wrap_inline20400" SRC="HTMLSlidesimg2.gif"  > '; 
$key = q/{figure}[H]centerscalebox0.75includegraphicshomespmadammHPCHPFCourseDiagramsIndepentExample1.pslabelIndepentExample1Visualisation:figcenter{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=523 HEIGHT=164 ALIGN=BOTTOM ALT="figure15613" SRC="HTMLSlidesimg132.gif"  > '; 
$key = q/{figure}[H]includegraphicshomespmadammHPCHPFCourseDiagramsCyclicDistribution.pslabelCYCLICDistributionVisualisation:fig{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=603 HEIGHT=218 ALIGN=BOTTOM ALT="figure12715" SRC="HTMLSlidesimg93.gif"  > '; 
$key = q/{displaymath}A=left(arraycccc1;SPMamp;2;SPMamp;3;SPMamp;45;SPMamp;6;SPMamp;7;SPMamp;8arrayright){displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=312 HEIGHT=33 ALIGN=BOTTOM ALT="displaymath21588" SRC="HTMLSlidesimg45.gif"  > '; 
$key = q/{figure}[H]hspace*3.0cmscalebox0.75includegraphicshomespmadammHPCHPFCourseDiagramsTransposed2DAlign.pslabelTransposed2DAlignmentVisualisation:fig{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=378 HEIGHT=420 ALIGN=BOTTOM ALT="figure13850" SRC="HTMLSlidesimg111.gif"  > '; 
$key = q/{table}[H]centertabular|r|l|r|hlineSource;SPMamp;Compiler;SPMamp;ExecTime(s)hlinehlinebff90;SPMamp;EPC;SPMamp;85.0;SPMamp;Sun(_inline$parallel$_inline)(1proc);SPMamp;111.0;SPMamp;Sun(_inline$parallel$_inline)(2proc);SPMamp;111.0hlinebfhpf;SPMamp;PGI(_inline$parallel$_inline)(1proc);SPMamp;127.5;SPMamp;PGI(_inline$parallel$_inline)(2proc);SPMamp;67.6hlinetabularcenter{table}/;
$cached_env_img{$key} = ' <IMG WIDTH=269 HEIGHT=102 ALIGN=BOTTOM ALT="table18397" SRC="HTMLSlidesimg164.gif"  > '; 
$key = q/{}includegraphicshomespmadammHPCHPFCourseDiagramsReverseStridedAlignment.ps{}/;
$cached_env_img{$key} = ' <IMG WIDTH=282 HEIGHT=206 ALIGN=BOTTOM ALT="tex2html_wrap22414" SRC="HTMLSlidesimg115.gif"  > '; 
$key = q/{_inline}$y_j${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=11 HEIGHT=13 ALIGN=MIDDLE ALT="tex2html_wrap_inline22598" SRC="HTMLSlidesimg156.gif"  > '; 
$key = q/{figure}[H]hspace*3.0cmincludegraphicshomespmadammHPCHPFCourseDiagramsNewAlignTemplateDCE.pslabelStridedTemplateAlignmentVisualisation:fig{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=256 HEIGHT=618 ALIGN=BOTTOM ALT="figure14599" SRC="HTMLSlidesimg125.gif"  > '; 
$key = q/{figure}[H]hspace*3.0cmincludegraphicshomespmadammHPCHPFCourseDiagramsScalarAlignment.pslabelAlignedScalarVisualisation:fig{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=266 HEIGHT=330 ALIGN=BOTTOM ALT="figure14778" SRC="HTMLSlidesimg129.gif"  > '; 
$key = q/{displaymath}ttUNPACK((6,5,4),MASK,FIELD)=left(arrayrrrfbox6;SPMamp;fbox5;SPMamp;17;SPMamp;7;SPMamp;fbox4arrayright){displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=404 HEIGHT=41 ALIGN=BOTTOM ALT="displaymath22178" SRC="HTMLSlidesimg75.gif"  > '; 
$key = q/{_inline}$lceilfrac504rceil=13${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=55 HEIGHT=23 ALIGN=MIDDLE ALT="tex2html_wrap_inline22244" SRC="HTMLSlidesimg86.gif"  > '; 
$key = q/{_inline}$2^10${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=17 HEIGHT=10 ALIGN=BOTTOM ALT="tex2html_wrap_inline22610" SRC="HTMLSlidesimg163.gif"  > '; 
$key = q/{_inline}$fracpi4${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=7 HEIGHT=19 ALIGN=MIDDLE ALT="tex2html_wrap_inline21324" SRC="HTMLSlidesimg16.gif"  > '; 
$key = q/{_inline}$#P${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=20 HEIGHT=21 ALIGN=MIDDLE ALT="tex2html_wrap_inline22256" SRC="HTMLSlidesimg89.gif"  > '; 
$key = q/{tabular}|p2.5in|p2.5in|hlinettBTESTtt(i,pos);SPMamp;bittestingttIANDtt(i,j);SPMamp;ANDttIBCLRtt(i,pos);SPMamp;clearbitttIBITStt(i,pos,len);SPMamp;bitextractionttIBSETtt(i,pos);SPMamp;setbitttIEORtt(i,j);SPMamp;exclusiveORttIORtt(i,j);SPMamp;inclusiveORttISHFTtt(i,shft);SPMamp;logicalshiftttISHFTCtt(i,shft);SPMamp;circularshiftttNOTtt(i);SPMamp;complementhlinettMVBITStt(ifr,ifrpos,len,ito,itopos);SPMamp;movebits(ttSUB-ROUTINE)hline{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=517 HEIGHT=179 ALIGN=BOTTOM ALT="tabular11249" SRC="HTMLSlidesimg61.gif"  > '; 
$key = q/{_inline}$20times20${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=43 HEIGHT=18 ALIGN=MIDDLE ALT="tex2html_wrap_inline22534" SRC="HTMLSlidesimg138.gif"  > '; 
$key = q/{}includegraphicshomespmadammHPCHPFCourseDiagramsBlockMCyclicMDistribution.ps{}/;
$cached_env_img{$key} = ' <IMG WIDTH=597 HEIGHT=297 ALIGN=BOTTOM ALT="tex2html_wrap22366" SRC="HTMLSlidesimg100.gif"  > '; 
$key = q/{displaymath}ttFSOURCE=left(arrayccc0;SPMamp;4;SPMamp;82;SPMamp;6;SPMamp;10arrayright){displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=325 HEIGHT=33 ALIGN=BOTTOM ALT="displaymath22076" SRC="HTMLSlidesimg65.gif"  > '; 
$key = q/{_inline}$ntimesm${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=35 HEIGHT=13 ALIGN=MIDDLE ALT="tex2html_wrap_inline22526" SRC="HTMLSlidesimg136.gif"  > '; 
$key = q/{_inline}$1times11${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=35 HEIGHT=16 ALIGN=MIDDLE ALT="tex2html_wrap_inline22566" SRC="HTMLSlidesimg146.gif"  > '; 
$key = q/{figure}centerincludegraphicshomespmadammHPCF90CourseDiagramsArrayFigurescenter{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=333 HEIGHT=318 ALIGN=BOTTOM ALT="figure6672" SRC="HTMLSlidesimg23.gif"  > '; 
$key = q/{_inline}$10^33${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=23 HEIGHT=11 ALIGN=BOTTOM ALT="tex2html_wrap_inline20500" SRC="HTMLSlidesimg4.gif"  > '; 
$key = q/{figure}[H]centerincludegraphicshomespmadammHPCF90CourseDiagramsReshapeIntrinsicDiagramcenter{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=243 HEIGHT=61 ALIGN=BOTTOM ALT="figure7458" SRC="HTMLSlidesimg36.gif"  > '; 
$key = q/{displaymath}mboxttB=left(arrayccsf1.0;SPMamp;sf2.0sf3.0;SPMamp;sf4.0arrayright){displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=301 HEIGHT=33 ALIGN=BOTTOM ALT="displaymath21539" SRC="HTMLSlidesimg40.gif"  > '; 
$key = q/{figure}[H]hspace*3.0cmincludegraphicshomespmadammHPCHPFCourseDiagramsMessagePassing.epslabelMessagePassing:fig{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=461 HEIGHT=182 ALIGN=BOTTOM ALT="figure12409" SRC="HTMLSlidesimg85.gif"  > '; 
$key = q/{figure}centerincludegraphicshomespmadammHPCF90CourseDiagramsArrayElementOrderingFigurecenter{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=292 HEIGHT=324 ALIGN=BOTTOM ALT="figure6781" SRC="HTMLSlidesimg25.gif"  > '; 
$key = q/{displaymath}mboxttI=left(arrayccfbox2;SPMamp;00;SPMamp;fbox2arrayright){displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=300 HEIGHT=41 ALIGN=BOTTOM ALT="displaymath21537" SRC="HTMLSlidesimg38.gif"  > '; 
$key = q/{}scalebox0.9includegraphicshomespmadammHPCF90CourseDiagramsModuleDiagram{}/;
$cached_env_img{$key} = ' <IMG WIDTH=284 HEIGHT=551 ALIGN=BOTTOM ALT="tex2html_wrap22006" SRC="HTMLSlidesimg53.gif"  > '; 
$key = q/{}includegraphicshomespmadammHPCHPFCourseDiagramsSORAccess.ps{}/;
$cached_env_img{$key} = ' <IMG WIDTH=217 HEIGHT=200 ALIGN=BOTTOM ALT="tex2html_wrap22290" SRC="HTMLSlidesimg99.gif"  > '; 
$key = q/{}includegraphicshomespmadammHPCHPFCourseDiagramsReplicatedAlignment.ps{}/;
$cached_env_img{$key} = ' <IMG WIDTH=243 HEIGHT=312 ALIGN=BOTTOM ALT="tex2html_wrap22426" SRC="HTMLSlidesimg119.gif"  > '; 
$key = q/{tabular}|l|p3.5in|hlinettABStt(a);SPMamp;absolutevaluettAINTtt(a);SPMamp;truncatesttatowholettREALnumberttANINTtt(a);SPMamp;nearestwholettREALnumberttCEILINGtt(a);SPMamp;smallestttINTEGERgreaterthanorequaltottREALnumberttCMPLXtt(x,y);SPMamp;converttottCOMPLEXttDBLEtt(x);SPMamp;converttottDOUBLEPRECISIONttDIMtt(x,y);SPMamp;positivedifferencettFLOORtt(a);SPMamp;biggestttINTEGERlessthanorequaltorealnumberttINTtt(a);SPMamp;truncates_inline$a$_inlineintoanttINTEGERttMAXtt(a1,a2,a3,...);SPMamp;themaximumvalueoftheargumentsttMINtt(a1,a2,a3,...);SPMamp;theminimumvalueoftheargumentsttMODtt(a,p);SPMamp;remainderfunctionttMODULOtt(a,p);SPMamp;modulofunctionttNINTtt(x);SPMamp;nearestttINTEGERtoattREALnumberttREALtt(a);SPMamp;convertstotheequivalentttREALvaluettSIGNtt(a,b);SPMamp;transferofsign---ttABStt(ttatt)tt*tt(ttbttttABStt(ttbtt)tt)hline{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=492 HEIGHT=258 ALIGN=BOTTOM ALT="tabular6278" SRC="HTMLSlidesimg18.gif"  > '; 
$key = q/{_inline}$y_i=2r_2j-1${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=75 HEIGHT=18 ALIGN=MIDDLE ALT="tex2html_wrap_inline22594" SRC="HTMLSlidesimg154.gif"  > '; 
$key = q/{}scalebox0.9epsfigfigure=homespmadammHPCF90CourseDiagramsStackExampleVisualisation{}/;
$cached_env_img{$key} = ' <IMG WIDTH=545 HEIGHT=312 ALIGN=BOTTOM ALT="tex2html_wrap22018" SRC="HTMLSlidesimg60.gif"  > '; 
$key = q/{_inline}$3times4${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=30 HEIGHT=18 ALIGN=MIDDLE ALT="tex2html_wrap_inline21486" SRC="HTMLSlidesimg29.gif"  > '; 
$key = q/{}scalebox1.2includegraphicshomespmadammHPCHPFCourseDiagramsMessagePassing.eps{}/;
$cached_env_img{$key} = ' <IMG WIDTH=553 HEIGHT=219 ALIGN=BOTTOM ALT="tex2html_wrap22232" SRC="HTMLSlidesimg84.gif"  > '; 
$key = q/{_inline}$5times3${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=29 HEIGHT=18 ALIGN=MIDDLE ALT="tex2html_wrap_inline21372" SRC="HTMLSlidesimg22.gif"  > '; 
$key = q/{tabular}|cc|l|hlinett.GT.;SPMamp;<verb_mark>97<verb_mark>;SPMamp;greaterthantt.GE.;SPMamp;<verb_mark>98<verb_mark>;SPMamp;greaterthanorequaltott.LE.;SPMamp;<verb_mark>99<verb_mark>;SPMamp;lessthanorequaltott.LT.;SPMamp;<verb_mark>100<verb_mark>;SPMamp;lessthantt.NE.;SPMamp;<verb_mark>101<verb_mark>;SPMamp;notequaltott.EQ.;SPMamp;<verb_mark>102<verb_mark>;SPMamp;equaltohline{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=232 HEIGHT=98 ALIGN=BOTTOM ALT="tabular3505" SRC="HTMLSlidesimg10.gif"  > '; 
$key = q/{_inline}$1leqjleqn${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=56 HEIGHT=19 ALIGN=MIDDLE ALT="tex2html_wrap_inline22590" SRC="HTMLSlidesimg152.gif"  > '; 
$key = q/{displaymath}mboxttArray=left(arrayccccc0;SPMamp;-1;SPMamp;1;SPMamp;6;SPMamp;-41;SPMamp;-2;SPMamp;5;SPMamp;4;SPMamp;-33;SPMamp;8;SPMamp;3;SPMamp;-7;SPMamp;0arrayright){displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=352 HEIGHT=49 ALIGN=BOTTOM ALT="displaymath21646" SRC="HTMLSlidesimg47.gif"  > '; 
$key = q/{_inline}$;SPMlt;!${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=8 HEIGHT=17 ALIGN=MIDDLE ALT="tex2html_wrap_inline20398" SRC="HTMLSlidesimg1.gif"  > '; 
$key = q/{}epsfigfigure=homespmadammHPCF90CourseDiagramsReshapeIntrinsicDiagram{}/;
$cached_env_img{$key} = ' <IMG WIDTH=243 HEIGHT=61 ALIGN=BOTTOM ALT="tex2html_wrap21532" SRC="HTMLSlidesimg36.gif"  > '; 
$key = q/{}includegraphicshomespmadammHPCHPFCourseDiagramsBlockCyclicDistribution.ps{}/;
$cached_env_img{$key} = ' <IMG WIDTH=401 HEIGHT=295 ALIGN=BOTTOM ALT="tex2html_wrap22282" SRC="HTMLSlidesimg95.gif"  > '; 
$key = q/{figure}[H]hspace*4.5cmincludegraphicshomespmadammHPCHPFCourseDiagramsSORAccess.pslabelSORAccessPatterns:fig{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=217 HEIGHT=200 ALIGN=BOTTOM ALT="figure13047" SRC="HTMLSlidesimg99.gif"  > '; 
$key = q/{displaymath}ttA=left(arrayccc1;SPMamp;5;SPMamp;93;SPMamp;7;SPMamp;11arrayright){displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=304 HEIGHT=33 ALIGN=BOTTOM ALT="displaymath22119" SRC="HTMLSlidesimg73.gif"  > '; 
$key = q/{displaymath}foralljmboxalignttA(jmboxtt)andttA(jmboxtt)withttC(jmboxtt){displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=344 HEIGHT=13 ALIGN=BOTTOM ALT="displaymath22378" SRC="HTMLSlidesimg105.gif"  > '; 
$key = q/{displaymath}ttFIELD=left(arrayrrr9;SPMamp;5;SPMamp;17;SPMamp;7;SPMamp;3arrayright){displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=315 HEIGHT=33 ALIGN=BOTTOM ALT="displaymath22176" SRC="HTMLSlidesimg74.gif"  > '; 
$key = q/{}rotatebox270scalebox0.75includegraphicshomespmadammHPCHPFCourseDiagramsNewVariablesExample1.ps{}/;
$cached_env_img{$key} = ' <IMG WIDTH=618 HEIGHT=382 ALIGN=BOTTOM ALT="tex2html_wrap22530" SRC="HTMLSlidesimg135.gif"  > '; 
$key = q/{}includegraphicshomespmadammHPCHPFCourseDiagramsBlockDistribution.ps{}/;
$cached_env_img{$key} = ' <IMG WIDTH=591 HEIGHT=193 ALIGN=BOTTOM ALT="tex2html_wrap22262" SRC="HTMLSlidesimg91.gif"  > '; 
$key = q/{_inline}$1leqileq2n${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=61 HEIGHT=19 ALIGN=MIDDLE ALT="tex2html_wrap_inline22588" SRC="HTMLSlidesimg150.gif"  > '; 
$key = q/{}epsfigfigure=homespmadammHPCF90CourseDiagramsImplementationOfAStack{}/;
$cached_env_img{$key} = ' <IMG WIDTH=490 HEIGHT=358 ALIGN=BOTTOM ALT="tex2html_wrap22014" SRC="HTMLSlidesimg58.gif"  > '; 
$key = q/{_inline}$i^th${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=15 HEIGHT=11 ALIGN=BOTTOM ALT="tex2html_wrap_inline21292" SRC="HTMLSlidesimg12.gif"  > '; 
$key = q/{_inline}$x_j${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=12 HEIGHT=13 ALIGN=MIDDLE ALT="tex2html_wrap_inline22596" SRC="HTMLSlidesimg155.gif"  > '; 
$key = q/{}epsfigfigure=homespmadammHPCF90CourseDiagramsTransferIntrinsicDiagram{}/;
$cached_env_img{$key} = ' <IMG WIDTH=265 HEIGHT=170 ALIGN=BOTTOM ALT="tex2html_wrap22220" SRC="HTMLSlidesimg78.gif"  > '; 
$key = q/{figure}[H]centerincludegraphicshomespmadammHPCF90CourseDiagramsModuleDiagramcenter{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=316 HEIGHT=612 ALIGN=BOTTOM ALT="figure10525" SRC="HTMLSlidesimg54.gif"  > '; 
$key = q/{displaymath}mboxttArray=left(arrayccccc0;SPMamp;-1;SPMamp;1;SPMamp;fbox6;SPMamp;-41;SPMamp;-2;SPMamp;5;SPMamp;4;SPMamp;-33;SPMamp;;SPMamp;3;SPMamp;-7;SPMamp;0arrayright){displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=352 HEIGHT=50 ALIGN=BOTTOM ALT="displaymath21648" SRC="HTMLSlidesimg48.gif"  > '; 
$key = q/{figure}[H]centerincludegraphicshomespmadammHPCF90CourseDiagramsTransferIntrinsicDiagramcenter{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=265 HEIGHT=170 ALIGN=BOTTOM ALT="figure12154" SRC="HTMLSlidesimg78.gif"  > '; 
$key = q/{displaymath}B=left(arrayccc0;SPMamp;3;SPMamp;57;SPMamp;4;SPMamp;8arrayright){displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=303 HEIGHT=33 ALIGN=BOTTOM ALT="displaymath21657" SRC="HTMLSlidesimg50.gif"  > '; 
$key = q/{}includegraphicshomespmadammHPCF90CourseDiagramsBitVariablesDiagram2{}/;
$cached_env_img{$key} = ' <IMG WIDTH=234 HEIGHT=185 ALIGN=BOTTOM ALT="tex2html_wrap22070" SRC="HTMLSlidesimg62.gif"  > '; 
$key = q/{figure}[H]centerscalebox0.9includegraphicshomespmadammHPCF90CourseDiagramsStackExampleVisualisationcenter{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=545 HEIGHT=312 ALIGN=BOTTOM ALT="figure10778" SRC="HTMLSlidesimg60.gif"  > '; 
$key = q/{_inline}$forall${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=8 HEIGHT=11 ALIGN=BOTTOM ALT="tex2html_wrap_inline22386" SRC="HTMLSlidesimg107.gif"  > '; 
$key = q/{tabular}cl|clSymbol;SPMamp;Description;SPMamp;Symbol;SPMamp;Descriptionhline;SPMamp;space;SPMamp;tt=;SPMamp;equal<verb_mark>44<verb_mark>;SPMamp;plus;SPMamp;<verb_mark>45<verb_mark>;SPMamp;minus<verb_mark>46<verb_mark>;SPMamp;asterisk;SPMamp;tt;SPMamp;slashtt(;SPMamp;leftparen;SPMamp;tt);SPMamp;rightparen<verb_mark>47<verb_mark>;SPMamp;comma;SPMamp;<verb_mark>48<verb_mark>;SPMamp;period<verb_mark>49<verb_mark>;SPMamp;singlequote;SPMamp;<verb_mark>50<verb_mark>;SPMamp;doublequote<verb_mark>51<verb_mark>;SPMamp;colon;SPMamp;<verb_mark>57<verb_mark>;SPMamp;semicolontt!;SPMamp;shriek;SPMamp;tt&;SPMamp;ampersand<verb_mark>52<verb_mark>;SPMamp;percent;SPMamp;<verb_mark>53<verb_mark>;SPMamp;lessthan<verb_mark>54<verb_mark>;SPMamp;greaterthan;SPMamp;<verb_mark>55<verb_mark>;SPMamp;dollar<verb_mark>56<verb_mark>;SPMamp;questionmark;SPMamp;;SPMamp;{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=311 HEIGHT=195 ALIGN=BOTTOM ALT="tabular2143" SRC="HTMLSlidesimg6.gif"  > '; 
$key = q/{}includegraphicshomespmadammHPCHPFCourseDiagramsCollapsedAlignment.ps{}/;
$cached_env_img{$key} = ' <IMG WIDTH=218 HEIGHT=325 ALIGN=BOTTOM ALT="tex2html_wrap22420" SRC="HTMLSlidesimg116.gif"  > '; 
$key = q/{displaymath}ttSPREADtt(A,2,4)=left(arrayrrrr5;SPMamp;5;SPMamp;5;SPMamp;57;SPMamp;7;SPMamp;7;SPMamp;7arrayright){displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=350 HEIGHT=33 ALIGN=BOTTOM ALT="displaymath22108" SRC="HTMLSlidesimg70.gif"  > '; 
$key = q/{figure}[h]hspace*3.0cmincludegraphicshomespmadammHPCHPFCourseDiagramsStridedAlignment.pslabelStridedAlignmentVisualisation:fig{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=267 HEIGHT=212 ALIGN=BOTTOM ALT="figure13937" SRC="HTMLSlidesimg113.gif"  > '; 
$key = q/{_inline}$4times4${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=30 HEIGHT=16 ALIGN=MIDDLE ALT="tex2html_wrap_inline22546" SRC="HTMLSlidesimg143.gif"  > '; 
$key = q/{}includegraphicshomespmadammHPCHPFCourseDiagramsTransposed2DAlign.ps{}/;
$cached_env_img{$key} = ' <IMG WIDTH=503 HEIGHT=561 ALIGN=BOTTOM ALT="tex2html_wrap22398" SRC="HTMLSlidesimg110.gif"  > '; 
$key = q/{figure}centerincludegraphicshomespmadammHPCF90CourseDiagramsArrayConformanceDiagramcenter{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=291 HEIGHT=291 ALIGN=BOTTOM ALT="figure6970" SRC="HTMLSlidesimg27.gif"  > '; 
$key = q/{}scalebox0.8includegraphicshomespmadammHPCHPFCourseDiagramsIndepentExample1.ps{}/;
$cached_env_img{$key} = ' <IMG WIDTH=558 HEIGHT=175 ALIGN=BOTTOM ALT="tex2html_wrap22518" SRC="HTMLSlidesimg131.gif"  > '; 
$key = q/{displaymath}ttFSOURCE=left(arrayccc0;SPMamp;4;SPMamp;fbox8fbox2;SPMamp;fbox6;SPMamp;10arrayright){displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=339 HEIGHT=41 ALIGN=BOTTOM ALT="displaymath22080" SRC="HTMLSlidesimg68.gif"  > '; 
$key = q/{_inline}$2times2${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=29 HEIGHT=16 ALIGN=MIDDLE ALT="tex2html_wrap_inline21528" SRC="HTMLSlidesimg35.gif"  > '; 
$key = q/{}includegraphicshomespmadammHPCHPFCourseDiagrams2DAlign.ps{}/;
$cached_env_img{$key} = ' <IMG WIDTH=503 HEIGHT=554 ALIGN=BOTTOM ALT="tex2html_wrap22390" SRC="HTMLSlidesimg108.gif"  > '; 
$key = q/{figure}[H]hspace*3.0cmincludegraphicshomespmadammHPCHPFCourseDiagramsAlignToSection.pslabelEmbeddedAlignmentVisualisation:fig{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=212 HEIGHT=264 ALIGN=BOTTOM ALT="figure14741" SRC="HTMLSlidesimg126.gif"  > '; 
$key = q/{_inline}$4times1${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=29 HEIGHT=16 ALIGN=MIDDLE ALT="tex2html_wrap_inline21490" SRC="HTMLSlidesimg31.gif"  > '; 
$key = q/{_inline}$#A${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=20 HEIGHT=21 ALIGN=MIDDLE ALT="tex2html_wrap_inline22254" SRC="HTMLSlidesimg88.gif"  > '; 
$key = q/{}fboxOptionalSlide{}/;
$cached_env_img{$key} = ' <IMG WIDTH=94 HEIGHT=22 ALIGN=BOTTOM ALT="tex2html_wrap22564" SRC="HTMLSlidesimg145.gif"  > '; 
$key = q/{}includegraphicshomespmadammHPCHPFCourseDiagramsAlignAB.ps{}/;
$cached_env_img{$key} = ' <IMG WIDTH=439 HEIGHT=270 ALIGN=BOTTOM ALT="tex2html_wrap22382" SRC="HTMLSlidesimg104.gif"  > '; 
$key = q/{_inline}$1timesn${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=30 HEIGHT=16 ALIGN=MIDDLE ALT="tex2html_wrap_inline21520" SRC="HTMLSlidesimg33.gif"  > '; 
$key = q/{figure}[H]hspace*3.0cmscalebox0.75includegraphicshomespmadammHPCHPFCourseDiagrams2DAlign.pslabel2DAlignmentVisualisation:fig{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=378 HEIGHT=416 ALIGN=BOTTOM ALT="figure13760" SRC="HTMLSlidesimg109.gif"  > '; 
$key = q/{displaymath}ttSPREADtt(A,1,4)=left(arrayrr5;SPMamp;75;SPMamp;75;SPMamp;75;SPMamp;7arrayright){displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=331 HEIGHT=65 ALIGN=BOTTOM ALT="displaymath22109" SRC="HTMLSlidesimg71.gif"  > '; 
$key = q/{figure}[H]centerincludegraphicshomespmadammHPCF90CourseDiagramsImplementationOfAStackcenter{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=490 HEIGHT=358 ALIGN=BOTTOM ALT="figure10701" SRC="HTMLSlidesimg58.gif"  > '; 
$key = q/{_inline}$bfx+ibfy${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=38 HEIGHT=19 ALIGN=MIDDLE ALT="tex2html_wrap_inline21294" SRC="HTMLSlidesimg13.gif"  > '; 

1;

