# LaTeX2HTML 96.1 (Feb 5, 1996)
# Associate images original text with physical files.

$key = q/{_inline}$(bfx,bfy)=(-3.47,19.7)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=126 HEIGHT=20 ALIGN=MIDDLE ALT="tex2html_wrap_inline2856" SRC="HTMLQuestionsimg26.gif"  > '; 
$key = q/{_inline}$igeqj${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=28 HEIGHT=19 ALIGN=MIDDLE ALT="tex2html_wrap_inline2952" SRC="HTMLQuestionsimg51.gif"  > '; 
$key = q/{tabular}|llll|hlinebfName;SPMamp;bfStatus;SPMamp;bfType;SPMamp;bfInitialValuehlinefeet;SPMamp;variable;SPMamp;integer;SPMamp;-miles;SPMamp;variable;SPMamp;real;SPMamp;-town;SPMamp;variable;SPMamp;character(_inline$leq$_inline20letters);SPMamp;-home_town;SPMamp;constant;SPMamp;character;SPMamp;_inline$;SPMlt;!$_inlineem~yourhometown_inline$!;SPMgt;$_inlinein_uk;SPMamp;constant;SPMamp;logical;SPMamp;_inline$;SPMlt;!$_inlineem~isyourhometowninUK?_inline$!;SPMgt;$_inlinesin_half;SPMamp;constant;SPMamp;real;SPMamp;_inline$sin(0.5)=0.47942554$_inlinehline{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=501 HEIGHT=114 ALIGN=BOTTOM ALT="tabular1211" SRC="HTMLQuestionsimg2.gif"  > '; 
$key = q/{_inline}$theta=77^circ${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=44 HEIGHT=11 ALIGN=BOTTOM ALT="tex2html_wrap_inline2814" SRC="HTMLQuestionsimg12.gif"  > '; 
$key = q/{displaymath}B=left(arrayrrr1;SPMamp;2;SPMamp;34;SPMamp;5;SPMamp;67;SPMamp;8;SPMamp;9arrayright){displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=304 HEIGHT=49 ALIGN=BOTTOM ALT="displaymath2979" SRC="HTMLQuestionsimg59.gif"  > '; 
$key = q/{_inline}$(x_i,i=1,n)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=70 HEIGHT=20 ALIGN=MIDDLE ALT="tex2html_wrap_inline2904" SRC="HTMLQuestionsimg39.gif"  > '; 
$key = q/{displaymath}(a+bbfi)^n=1timesunderbrace(a+bbfi)timescdotstimes(a+bbfi)_n{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=365 HEIGHT=31 ALIGN=BOTTOM ALT="displaymath2934" SRC="HTMLQuestionsimg50.gif"  > '; 
$key = q/{displaymath}bfy=a^2bfx+bbfx+c{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=300 HEIGHT=15 ALIGN=BOTTOM ALT="displaymath2864" SRC="HTMLQuestionsimg27.gif"  > '; 
$key = q/{}includegraphicshomespmadammHPCHPFCourseDiagramsLifeInitialBoard.eps{}/;
$cached_env_img{$key} = ' <IMG WIDTH=195 HEIGHT=195 ALIGN=BOTTOM ALT="tex2html_wrap3004" SRC="HTMLQuestionsimg63.gif"  > '; 
$key = q/{_inline}$underlinex${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=8 HEIGHT=11 ALIGN=MIDDLE ALT="tex2html_wrap_inline3074" SRC="HTMLQuestionsimg82.gif"  > '; 
$key = q/{_inline}$theta=90^circ${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=44 HEIGHT=11 ALIGN=BOTTOM ALT="tex2html_wrap_inline2822" SRC="HTMLQuestionsimg15.gif"  > '; 
$key = q/{displaymath}s=sqrtfracsum^n_i=1(x_i-m)^2n{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=315 HEIGHT=33 ALIGN=BOTTOM ALT="displaymath2902" SRC="HTMLQuestionsimg40.gif"  > '; 
$key = q/{_inline}$theta=100^circ${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=51 HEIGHT=11 ALIGN=BOTTOM ALT="tex2html_wrap_inline2826" SRC="HTMLQuestionsimg17.gif"  > '; 
$key = q/{displaymath}frac(a+bbfi)(x+ybfi)=frac(a+bbfi)times(x-ybfi)x^2+y^2{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=337 HEIGHT=31 ALIGN=BOTTOM ALT="displaymath2933" SRC="HTMLQuestionsimg48.gif"  > '; 
$key = q/{displaymath}A=left(arrayrrrr1;SPMamp;2;SPMamp;3;SPMamp;4arrayright){displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=309 HEIGHT=17 ALIGN=BOTTOM ALT="displaymath2976" SRC="HTMLQuestionsimg56.gif"  > '; 
$key = q/{_inline}$theta=0^circ${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=37 HEIGHT=11 ALIGN=BOTTOM ALT="tex2html_wrap_inline2818" SRC="HTMLQuestionsimg14.gif"  > '; 
$key = q/{_inline}$(bfx,bfy)=(0.0,10.0)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=108 HEIGHT=20 ALIGN=MIDDLE ALT="tex2html_wrap_inline2850" SRC="HTMLQuestionsimg25.gif"  > '; 
$key = q/{_inline}$theta=437^circ${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=51 HEIGHT=11 ALIGN=BOTTOM ALT="tex2html_wrap_inline2830" SRC="HTMLQuestionsimg18.gif"  > '; 
$key = q/{displaymath}sintheta=fracyr{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=276 HEIGHT=24 ALIGN=BOTTOM ALT="displaymath2800" SRC="HTMLQuestionsimg20.gif"  > '; 
$key = q/{_inline}$A=LcdotU${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=57 HEIGHT=11 ALIGN=BOTTOM ALT="tex2html_wrap_inline3050" SRC="HTMLQuestionsimg69.gif"  > '; 
$key = q/{_inline}$arctan${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=37 HEIGHT=9 ALIGN=BOTTOM ALT="tex2html_wrap_inline2762" SRC="HTMLQuestionsimg6.gif"  > '; 
$key = q/{}scalebox0.7includegraphicshomespmadammtexbincrest.ps{}/;
$cached_env_img{$key} = ' <IMG WIDTH=414 HEIGHT=225 ALIGN=BOTTOM ALT="tex2html_wrap2746" SRC="HTMLQuestionsimg1.gif"  > '; 
$key = q/{_inline}$i=mboxihalf+1${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=71 HEIGHT=20 ALIGN=MIDDLE ALT="tex2html_wrap_inline2960" SRC="HTMLQuestionsimg54.gif"  > '; 
$key = q/{displaymath}A=left(arrayrrrr4;SPMamp;1;SPMamp;2;SPMamp;3arrayright){displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=309 HEIGHT=17 ALIGN=BOTTOM ALT="displaymath2978" SRC="HTMLQuestionsimg58.gif"  > '; 
$key = q/{displaymath}bfx=frac-bpmsqrtb^2-4ac2a{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=310 HEIGHT=31 ALIGN=BOTTOM ALT="displaymath2865" SRC="HTMLQuestionsimg28.gif"  > '; 
$key = q/{tabular}|cc|cc|cc|0;SPMamp;;SPMamp;;SPMamp;;SPMamp;;SPMamp;1;SPMamp;emi;SPMamp;1_inline$cdot$_inline;SPMamp;emx;SPMamp;1_inline$cdotcdot$_inline;SPMamp;emc2;SPMamp;emii;SPMamp;2_inline$cdot$_inline;SPMamp;emxx;SPMamp;2_inline$cdotcdot$_inline;SPMamp;emcc3;SPMamp;emiii;SPMamp;3_inline$cdot$_inline;SPMamp;emxxx;SPMamp;3_inline$cdotcdot$_inline;SPMamp;emccc4;SPMamp;emiv;SPMamp;4_inline$cdot$_inline;SPMamp;emxl;SPMamp;4_inline$cdotcdot$_inline;SPMamp;emcd5;SPMamp;emv;SPMamp;5_inline$cdot$_inline;SPMamp;eml;SPMamp;5_inline$cdotcdot$_inline;SPMamp;emd6;SPMamp;emvi;SPMamp;6_inline$cdot$_inline;SPMamp;emlx;SPMamp;6_inline$cdotcdot$_inline;SPMamp;emdc7;SPMamp;emvii;SPMamp;7_inline$cdot$_inline;SPMamp;emlxx;SPMamp;7_inline$cdotcdot$_inline;SPMamp;emdcc8;SPMamp;emviii;SPMamp;8_inline$cdot$_inline;SPMamp;emlxxx;SPMamp;8_inline$cdotcdot$_inline;SPMamp;emdccc9;SPMamp;emix;SPMamp;9_inline$cdot$_inline;SPMamp;emxc;SPMamp;9_inline$cdotcdot$_inline;SPMamp;emcm{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=193 HEIGHT=162 ALIGN=BOTTOM ALT="tabular1343" SRC="HTMLQuestionsimg7.gif"  > '; 
$key = q/{displaymath}b^2-4ac=0{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=286 HEIGHT=13 ALIGN=BOTTOM ALT="displaymath2866" SRC="HTMLQuestionsimg29.gif"  > '; 
$key = q/{_inline}$jin(mboxtti+1:n${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=63 HEIGHT=20 ALIGN=MIDDLE ALT="tex2html_wrap_inline2888" SRC="HTMLQuestionsimg32.gif"  > '; 
$key = q/{displaymath}A=left(arrayrrrr2;SPMamp;3;SPMamp;4;SPMamp;1arrayright){displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=309 HEIGHT=17 ALIGN=BOTTOM ALT="displaymath2977" SRC="HTMLQuestionsimg57.gif"  > '; 
$key = q/{_inline}$underliney${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=8 HEIGHT=12 ALIGN=MIDDLE ALT="tex2html_wrap_inline3060" SRC="HTMLQuestionsimg76.gif"  > '; 
$key = q/{}includegraphicshomespmadammHPCF90CourseDiagramsControlCirclePoint.eps{}/;
$cached_env_img{$key} = ' <IMG WIDTH=186 HEIGHT=83 ALIGN=BOTTOM ALT="tex2html_wrap2832" SRC="HTMLQuestionsimg19.gif"  > '; 
$key = q/{displaymath}A=left(arraycccc0;SPMamp;-5;SPMamp;8;SPMamp;33;SPMamp;4;SPMamp;-1;SPMamp;21;SPMamp;5;SPMamp;6;SPMamp;-4arrayright){displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=329 HEIGHT=49 ALIGN=BOTTOM ALT="displaymath2892" SRC="HTMLQuestionsimg33.gif"  > '; 
$key = q/{_inline}$ngeq0${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=32 HEIGHT=19 ALIGN=MIDDLE ALT="tex2html_wrap_inline2940" SRC="HTMLQuestionsimg49.gif"  > '; 
$key = q/{_inline}$y=Acdotunderlinex${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=53 HEIGHT=21 ALIGN=MIDDLE ALT="tex2html_wrap_inline3006" SRC="HTMLQuestionsimg64.gif"  > '; 
$key = q/{_inline}$mboxihalf${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=27 HEIGHT=10 ALIGN=BOTTOM ALT="tex2html_wrap_inline2958" SRC="HTMLQuestionsimg53.gif"  > '; 
$key = q/{_inline}$Ucdotunderlinex=underliney${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=53 HEIGHT=18 ALIGN=MIDDLE ALT="tex2html_wrap_inline3068" SRC="HTMLQuestionsimg80.gif"  > '; 
$key = q/{displaymath}(a+bbfi)times(x+ybfi)=(atimesx-btimesy)+(atimesy+btimesx)bfi{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=408 HEIGHT=13 ALIGN=BOTTOM ALT="displaymath2932" SRC="HTMLQuestionsimg47.gif"  > '; 
$key = q/{_inline}$(bfx,bfy)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=30 HEIGHT=20 ALIGN=MIDDLE ALT="tex2html_wrap_inline2808" SRC="HTMLQuestionsimg10.gif"  > '; 
$key = q/{_inline}$Lcdotunderliney=underlineb${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=50 HEIGHT=20 ALIGN=MIDDLE ALT="tex2html_wrap_inline3066" SRC="HTMLQuestionsimg79.gif"  > '; 
$key = q/{_inline}$4timesarctan1.0=pi${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=106 HEIGHT=18 ALIGN=MIDDLE ALT="tex2html_wrap_inline2760" SRC="HTMLQuestionsimg5.gif"  > '; 
$key = q/{_inline}$8times8${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=29 HEIGHT=18 ALIGN=MIDDLE ALT="tex2html_wrap_inline2882" SRC="HTMLQuestionsimg30.gif"  > '; 
$key = q/{displaymath}(a+bbfi)+(x+ybfi)=(a+x)+(b+y)bfi{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=362 HEIGHT=13 ALIGN=BOTTOM ALT="displaymath2930" SRC="HTMLQuestionsimg45.gif"  > '; 
$key = q/{_inline}$|x_i|,i=1,n${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=68 HEIGHT=21 ALIGN=MIDDLE ALT="tex2html_wrap_inline2898" SRC="HTMLQuestionsimg36.gif"  > '; 
$key = q/{_inline}$|z|^2;SPMgt;4.0${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=54 HEIGHT=22 ALIGN=MIDDLE ALT="tex2html_wrap_inline3024" SRC="HTMLQuestionsimg68.gif"  > '; 
$key = q/{_inline}$C_ij=A_itimesB_j${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=82 HEIGHT=20 ALIGN=MIDDLE ALT="tex2html_wrap_inline2928" SRC="HTMLQuestionsimg44.gif"  > '; 
$key = q/{_inline}$|a_ij|${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=21 HEIGHT=21 ALIGN=MIDDLE ALT="tex2html_wrap_inline2900" SRC="HTMLQuestionsimg37.gif"  > '; 
$key = q/{_inline}$theta${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=6 HEIGHT=10 ALIGN=BOTTOM ALT="tex2html_wrap_inline2806" SRC="HTMLQuestionsimg9.gif"  > '; 
$key = q/{displaymath}costheta=fracxr{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=277 HEIGHT=24 ALIGN=BOTTOM ALT="displaymath2801" SRC="HTMLQuestionsimg21.gif"  > '; 
$key = q/{_inline}$p_i=p_i-1+i${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=75 HEIGHT=18 ALIGN=MIDDLE ALT="tex2html_wrap_inline2914" SRC="HTMLQuestionsimg43.gif"  > '; 
$key = q/{_inline}$(bfx,bfy)=(2.7,11.7)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=108 HEIGHT=20 ALIGN=MIDDLE ALT="tex2html_wrap_inline2838" SRC="HTMLQuestionsimg22.gif"  > '; 
$key = q/{displaymath}B=left(arrayrrr3;SPMamp;1;SPMamp;26;SPMamp;4;SPMamp;59;SPMamp;7;SPMamp;8arrayright){displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=304 HEIGHT=49 ALIGN=BOTTOM ALT="displaymath2981" SRC="HTMLQuestionsimg61.gif"  > '; 
$key = q/{_inline}$i^mboxth${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=17 HEIGHT=15 ALIGN=BOTTOM ALT="tex2html_wrap_inline2910" SRC="HTMLQuestionsimg41.gif"  > '; 
$key = q/{_inline}$bfr=20${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=37 HEIGHT=10 ALIGN=BOTTOM ALT="tex2html_wrap_inline2824" SRC="HTMLQuestionsimg16.gif"  > '; 
$key = q/{_inline}$j;SPMgt;mboxtti${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=30 HEIGHT=19 ALIGN=MIDDLE ALT="tex2html_wrap_inline2886" SRC="HTMLQuestionsimg31.gif"  > '; 
$key = q/{displaymath}(a+bbfi)-(x+ybfi)=(a-x)+(b-y)bfi{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=362 HEIGHT=13 ALIGN=BOTTOM ALT="displaymath2931" SRC="HTMLQuestionsimg46.gif"  > '; 
$key = q/{_inline}$bfr=12${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=37 HEIGHT=9 ALIGN=BOTTOM ALT="tex2html_wrap_inline2812" SRC="HTMLQuestionsimg11.gif"  > '; 
$key = q/{_inline}$(bfx,bfy)=(10.0,0.0)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=108 HEIGHT=20 ALIGN=MIDDLE ALT="tex2html_wrap_inline2844" SRC="HTMLQuestionsimg24.gif"  > '; 
$key = q/{_inline}$X=Z^2+C${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=73 HEIGHT=20 ALIGN=MIDDLE ALT="tex2html_wrap_inline3010" SRC="HTMLQuestionsimg66.gif"  > '; 
$key = q/{displaymath}mboxttX=left(arrayc1.5-1.91.7-1.20.3arrayright){displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=292 HEIGHT=81 ALIGN=BOTTOM ALT="displaymath2895" SRC="HTMLQuestionsimg35.gif"  > '; 
$key = q/{displaymath}mboxttA=left(arrayccc-4;SPMamp;5;SPMamp;96;SPMamp;-7;SPMamp;8arrayright){displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=311 HEIGHT=33 ALIGN=BOTTOM ALT="displaymath2894" SRC="HTMLQuestionsimg34.gif"  > '; 
$key = q/{_inline}$bfr${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=6 HEIGHT=6 ALIGN=BOTTOM ALT="tex2html_wrap_inline2804" SRC="HTMLQuestionsimg8.gif"  > '; 
$key = q/{displaymath}B=left(arrayrrr7;SPMamp;8;SPMamp;91;SPMamp;2;SPMamp;34;SPMamp;5;SPMamp;6arrayright){displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=304 HEIGHT=49 ALIGN=BOTTOM ALT="displaymath2980" SRC="HTMLQuestionsimg60.gif"  > '; 
$key = q/{_inline}$j=mboxihalf${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=51 HEIGHT=21 ALIGN=MIDDLE ALT="tex2html_wrap_inline2962" SRC="HTMLQuestionsimg55.gif"  > '; 
$key = q/{_inline}$bfr=1000${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=51 HEIGHT=10 ALIGN=BOTTOM ALT="tex2html_wrap_inline2816" SRC="HTMLQuestionsimg13.gif"  > '; 
$key = q/{_inline}$mboxihalf=fraci+(j-i)2${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=83 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline2954" SRC="HTMLQuestionsimg52.gif"  > '; 
$key = q/{_inline}$NtimesN${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=41 HEIGHT=17 ALIGN=MIDDLE ALT="tex2html_wrap_inline2994" SRC="HTMLQuestionsimg62.gif"  > '; 
$key = q/{_inline}$ntimesn${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=32 HEIGHT=13 ALIGN=MIDDLE ALT="tex2html_wrap_inline3008" SRC="HTMLQuestionsimg65.gif"  > '; 
$key = q/{tabular}c|ccccc;SPMamp;A;SPMamp;B;SPMamp;C;SPMamp;D;SPMamp;EhlineA;SPMamp;0;SPMamp;120;SPMamp;180;SPMamp;202;SPMamp;300B;SPMamp;;SPMamp;0;SPMamp;175;SPMamp;340;SPMamp;404C;SPMamp;;SPMamp;;SPMamp;0;SPMamp;98;SPMamp;56D;SPMamp;;SPMamp;;SPMamp;;SPMamp;0;SPMamp;168E;SPMamp;;SPMamp;;SPMamp;;SPMamp;;SPMamp;0{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=198 HEIGHT=98 ALIGN=BOTTOM ALT="tabular1848" SRC="HTMLQuestionsimg38.gif"  > '; 
$key = q/{_inline}$p_i${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=11 HEIGHT=13 ALIGN=MIDDLE ALT="tex2html_wrap_inline2912" SRC="HTMLQuestionsimg42.gif"  > '; 
$key = q/{_inline}$bfr=10${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=37 HEIGHT=10 ALIGN=BOTTOM ALT="tex2html_wrap_inline2840" SRC="HTMLQuestionsimg23.gif"  > '; 

1;

