# LaTeX2HTML 96.1 (Feb 5, 1996)
# Associate labels original text with physical files.

$key = q/INDEPENDENTNEWVisualisationfig/;
$external_labels{$key} = 'HTMLSlidesnode220.html'; 
$key = q/FFT1uxaTab/;
$external_labels{$key} = 'HTMLSlidesnode281.html'; 
$key = q/BLOCKmCYCLICmDistributionfig/;
$external_labels{$key} = 'HTMLSlidesnode174.html'; 
$key = q/SORAccessPatternsfig/;
$external_labels{$key} = 'HTMLSlidesnode169.html'; 
$key = q/EmbeddedAlignmentVisualisationfig/;
$external_labels{$key} = 'HTMLSlidesnode200.html'; 
$key = q/2DProcessorGridfig/;
$external_labels{$key} = 'HTMLSlidesnode146.html'; 
$key = q/ReplicatedAlignmentVisualisationfig/;
$external_labels{$key} = 'HTMLSlidesnode190.html'; 
$key = q/TemplateAlignmentVisualisationfig/;
$external_labels{$key} = 'HTMLSlidesnode195.html'; 
$key = q/1DProcessorChainfig/;
$external_labels{$key} = 'HTMLSlidesnode146.html'; 
$key = q/STARDistributionVisualisationfig/;
$external_labels{$key} = 'HTMLSlidesnode163.html'; 
$key = q/2DGaussianEliminationVisualisation/;
$external_labels{$key} = 'HTMLSlidesnode192.html'; 
$key = q/PDE1uxaTab/;
$external_labels{$key} = 'HTMLSlidesnode281.html'; 
$key = q/BLOCKDistributionVisualisationfig/;
$external_labels{$key} = 'HTMLSlidesnode160.html'; 
$key = q/2DBlockMCyclicMDistribution/;
$external_labels{$key} = 'HTMLSlidesnode175.html'; 
$key = q/AlignedScalarVisualisationfig/;
$external_labels{$key} = 'HTMLSlidesnode201.html'; 
$key = q/2DDistributionVisualisationfig/;
$external_labels{$key} = 'HTMLSlidesnode162.html'; 
$key = q/AlignmentVisualisationfig/;
$external_labels{$key} = 'HTMLSlidesnode178.html'; 
$key = q/DistributionActualDummyArgumentsVisualisationfig/;
$external_labels{$key} = 'HTMLSlidesnode242.html'; 
$key = q/StridedTemplateAlignmentVisualisationfig/;
$external_labels{$key} = 'HTMLSlidesnode198.html'; 
$key = q/MessagePassingfig/;
$external_labels{$key} = 'HTMLSlidesnode151.html'; 
$key = q/ReverseStridedAlignmentVisualisationfig/;
$external_labels{$key} = 'HTMLSlidesnode184.html'; 
$key = q/CYCLICDistributionVisualisationfig/;
$external_labels{$key} = 'HTMLSlidesnode161.html'; 
$key = q/CollapsingDimensionVisualisationfig/;
$external_labels{$key} = 'HTMLSlidesnode189.html'; 
$key = q/2DAlignmentVisualisationfig/;
$external_labels{$key} = 'HTMLSlidesnode180.html'; 
$key = q/IndependentExample1Visualisationfig/;
$external_labels{$key} = 'HTMLSlidesnode218.html'; 
$key = q/DoubleNestedIndependentLoopfig/;
$external_labels{$key} = 'HTMLSlidesnode223.html'; 
$key = q/StridedAlignmentVisualisationfig/;
$external_labels{$key} = 'HTMLSlidesnode183.html'; 
$key = q/Transposed2DAlignmentVisualisationfig/;
$external_labels{$key} = 'HTMLSlidesnode182.html'; 

1;

